
--create table appointment (version integer, begin_ts timestamp(6) with time zone not null, duration timestamp(6) with time zone not null, appointment_uuid uuid not null, medi_stream_uuid uuid, patient_uuid uuid not null, primary key (appointment_uuid));
--create table appointments_simple (booked integer, finish_time time(6) not null, start_time time(6) not null, appointment_date timestamp(6), duration bigint, id bigint generated by default as identity, medistream_id bigint, start_ts timestamp(6) with time zone not null, appointment_uuid uuid not null, day_label varchar(255) not null, day_name varchar(255) not null, day_name_abbreviator varchar(255) not null, day_of_month varchar(255) not null, month_name varchar(255) not null, primary key (id));
--create table calender_day_data (id bigint generated by default as identity, day_of_month varchar(255) not null, week_day varchar(255) not null, primary key (id));
--create table event (finish timestamp(6), id bigint generated by default as identity, start timestamp(6), description varchar(255), title varchar(255), primary key (id));
--create table medistream (version integer, medi_stream_uuid uuid not null, room_uuid uuid unique, medi_stream_name varchar(36) not null, primary key (medi_stream_uuid));
--create table patient (version integer, patient_fallnummer bigint not null, patient_uuid uuid not null, room_uuid uuid unique, patient_nachname varchar(36) not null, patient_name varchar(36) not null, primary key (patient_uuid));
--create table post (date_added timestamp(6), date_modified timestamp(6), id bigint generated by default as identity, text varchar(255), primary key (id));
--create table room (beds integer not null, room_number integer not null, version integer, room_uuid uuid not null, room_name varchar(36) not null, primary key (room_uuid));

--insert into event(id, title, start, finish, description) values (1, 'event1', '2015-01-01 1:00:00', '2015-01-01 2:00:00', 'description1')
--insert into event(id, title, start, finish, description) values (2, 'event2', '2015-01-02 2:00:00', '2015-01-02 3:00:00', 'description1')
--insert into event(id, title, start, finish, description) values (3, 'event3', '2015-01-03 1:00:00', '2015-01-03 2:00:00', 'description1')
--insert into event(id, title, start, finish, description) values (4, 'event4', '2015-01-04 1:00:00', '2015-01-04 2:00:00', 'description1')